name: 'Build Docker images'

inputs:
  images:
    description: 'Docker image names to build and push'
  tag-name:
    description: 'Additional image tag name'
    default: ${{ github.ref_name }}
  context:
    description: 'Path to Dockerfile (defaults to root project directory)'
    default: .
  push:
    description: 'Pass "true" to push Docker images to registries'
    default: 'true'
  dockerhub-username:
    description: 'Optional username for DockerHub (if omitted, no push will be performed)'
  dockerhub-token:
    description: 'Optional access token for DockerHub (if omitted, no push will be performed)'
  ghcr-username:
    description: 'Username for GHCR'
    default: ${{ github.repository_owner }}
  ghcr-token:
    description: 'Optional access token for GHCR (if omitted, no push will be performed)'

runs:
  using: composite
  steps:
    - name: 'Check DockerHub'
      id: dockerhub
      env:
        DOCKERHUB_USERNAME: ${{ inputs.dockerhub-username }}
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
      run: |
        if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
          echo "enabled=true" >> $GITHUB_OUTPUT
        else
          echo "enabled=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: 'Check GHCR'
      id: ghcr
      env:
        GHCR_USERNAME: ${{ inputs.ghcr-username }}
        GHCR_TOKEN: ${{ inputs.ghcr-token }}
      run: |
        if [ -n "$GHCR_USERNAME" ] && [ -n "$GHCR_TOKEN" ]; then
          echo "enabled=true" >> $GITHUB_OUTPUT
        else
          echo "enabled=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: 'Determine Docker images'
      id: images
      env:
        INPUT_IMAGES: ${{ inputs.images }}
        REPO_NAME: ${{ github.repository }}
        DOCKERHUB_ENABLED: ${{ steps.dockerhub.outputs.enabled }}
        GHCR_ENABLED: ${{ steps.ghcr.outputs.enabled }}
      run: |
        if [ -n "$images" ]; then
          echo "custom=${INPUT_IMAGES}" >> $GITHUB_OUTPUT
        else
          if [[ "$DOCKERHUB_ENABLED" == "true" ]]; then
            image="$REPO_NAME"
            echo "dockerhub=${image}" >> $GITHUB_OUTPUT
          fi
          if [[ "$GHCR_ENABLED" == "true" ]]; then
            image="ghcr.io/${REPO_NAME}"
            echo "ghcr=${image}" >> $GITHUB_OUTPUT
          fi
        fi
      shell: bash

    - name: 'Generate image metadata'
      id: meta
      uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6
      with:
        images: |
          ${{ steps.images.outputs.custom }}
          ${{ steps.images.outputs.dockerhub }}
          ${{ steps.images.outputs.ghcr }}
        tags: |
          type=raw,value=latest,enable=${{ github.event_name != 'workflow_dispatch' }}
          type=semver,pattern={{version}}
          type=raw,value=${{ inputs.tag-name }},enable=${{ github.event_name == 'workflow_dispatch' }}

    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

    - name: 'Login to Docker Hub'
      if: ${{ steps.dockerhub.outputs.enabled == 'true' }}
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: 'Login to GHCR'
      if: ${{ steps.ghcr.outputs.enabled == 'true' }}
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username }}
        password: ${{ inputs.ghcr-token }}

    - name: 'Build and push'
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
