name: 'Install Composer packages'

inputs:
  dependencies:
    description: 'Dependency versions to install (defaults to "locked")'
    default: locked
  composer-options:
    description: 'Additional command options'
  working-directory:
    description: 'Overwrite working directory'
  ignore-cache:
    description: 'Define whether to ignore caches'

runs:
  using: composite
  steps:
    - name: 'Install Composer packages'
      uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
      with:
        dependency-versions: ${{ inputs.dependencies }}
        composer-options: ${{ inputs.composer-options }}
        working-directory: ${{ inputs.working-directory }}
        ignore-cache: ${{ inputs.ignore-cache }}
