name: 'Install Composer packages'

inputs:
  dependencies:
    description: 'Dependency versions to install (defaults to "locked")'
    default: locked
  composer-options:
    description: 'Additional command options'
  working-directory:
    description: 'Overwrite working directory'

runs:
  using: composite
  steps:
    - name: 'Install Composer packages'
      uses: ramsey/composer-install@5c2bcf28d7b060ef3c601d7b476d5430a7b46c27 #v4
      with:
        dependency-versions: ${{ inputs.dependencies }}
        composer-options: ${{ inputs.composer-options }}
        working-directory: ${{ inputs.working-directory }}
