name: 'Validate composer.json file'

inputs:
  path:
    description: 'Path to composer.json'
    required: false

runs:
  using: composite
  steps:
    - name: 'Validate composer.json'
      run: composer validate ${{ inputs.path }}
      shell: bash
