name: 'Build documentation'

inputs:
  command:
    description: 'npm script to render pages'
    default: docs

runs:
  using: composite
  steps:
    - name: 'Setup Node'
      uses: eliashaeussler/gha/.github/actions/setup-node@0.3.3

    - name: 'Install npm packages'
      uses: eliashaeussler/gha/.github/actions/npm-install@0.3.3

    - name: 'Render documentation'
      env:
        BUILD_COMMAND: ${{ inputs.command }}
      run: npm run "$BUILD_COMMAND"
      shell: bash
