name: 'Setup Git environment'

inputs:
  commit-author-name:
    description: 'Author name used for Git commits'
    default: 'Elias Häußler'
  commit-author-email:
    description: 'Author email used for Git commits'
    default: 'elias@haeussler.dev'
  signing-key:
    description: 'Optional GPG key ID used to sign commits and tags'

runs:
  using: composite
  steps:
    - name: 'Configure Git user'
      env:
        COMMIT_AUTHOR_NAME: ${{ inputs.commit-author-name }}
        COMMIT_AUTHOR_EMAIL: ${{ inputs.commit-author-email }}
      run: |
        git config user.email "$COMMIT_AUTHOR_EMAIL"
        git config user.name "$COMMIT_AUTHOR_NAME"
      shell: bash

    - name: 'Configure Git signing key'
      if: ${{ inputs.signing-key }}
      env:
        SIGNING_KEY: ${{ inputs.signing-key }}
      run: |
        git config --global --unset gpg.format || true
        git config --global user.signingkey "$SIGNING_KEY"
        git config --global commit.gpgsign true
        git config --global tag.gpgSign true
      shell: bash
