name: 'Checkout'

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
  fetch-depth:
    description: 'Number of commits to fetch (defaults to "1")'
    default: '1'
  persist-credentials:
    description: 'Whether to configure the token or SSH key with the local git config (defaults to "false")'
    default: 'false'
  egress-policy:
    description: 'Policy for outbound traffic (defaults to "block")'
    default: block
  allowed-endpoints:
    description: 'List of allowed outbound endpoints'

runs:
  using: composite
  steps:
    - name: 'Determine allowed endpoints'
      id: endpoints
      run: |
        filename="$(realpath "${GITHUB_ACTION_PATH}/../../config/allowed-endpoints.txt")"

        if [ ! -f "$filename" ]; then
          echo "::error::Config file for allowed endpoints could not be found."
          exit 1
        fi

        endpoints="$(cat "$filename" | tr '\n' ' ')"
        echo "endpoints=${endpoints}" >> $GITHUB_OUTPUT
      shell: bash

    - name: 'Harden Runner'
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      if: ${{ success() }}
      with:
        egress-policy: ${{ inputs.egress-policy }}
        token: ${{ inputs.token }}
        allowed-endpoints: >
          ${{ steps.endpoints.outputs.endpoints }}
          ${{ inputs.allowed-endpoints }}

    - name: 'Checkout'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        persist-credentials: ${{ inputs.persist-credentials }}
