name: 'Checkout'

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
  fetch-depth:
    description: 'Number of commits to fetch (defaults to "1")'
    default: '1'
  persist-credentials:
    description: 'Whether to configure the token or SSH key with the local git config (defaults to "false")'
    default: 'false'
  egress-policy:
    description: 'Policy for outbound traffic (defaults to "block")'
    default: block
  allowed-endpoints:
    description: 'List of allowed outbound endpoints'

runs:
  using: composite
  steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: ${{ inputs.egress-policy }}
        token: ${{ inputs.token }}
        allowed-endpoints: >
          _pgpkey-https._tcp.keys.openpgp.org:443
          api.crowdin.com:443
          api.typo3.org:443
          artifacts.setup-php.com:443
          auth.docker.io:443
          cdn.jsdelivr.net:443
          coveralls.io:443
          ddev.com:443
          dl.cloudsmith.io:443
          docs.typo3.org:443
          extensions.typo3.org:443
          getcomposer.org:443
          ghcr.io:443
          keys.openpgp.org:443
          packagist.org:443
          phar.io:443
          pkg-containers.githubusercontent.com:443
          production.cloudfront.docker.com:443
          raw.githubusercontent.com:443
          registry-1.docker.io:443
          registry.npmjs.org:443
          release-assets.githubusercontent.com:443
          repo.packagist.org:443
          setup-php.com:443
          ${{ inputs.allowed-endpoints }}

    - name: 'Checkout'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        persist-credentials: ${{ inputs.persist-credentials }}
