name: 'Assure current tag is a version tag'

inputs:
  tag-name:
    description: 'The tag name to check (defaults to the current ref_name)'
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: 'Check tag'
      id: check-tag
      uses: eliashaeussler/gha/.github/actions/is-tag@0.4.0
      with:
        tag-name: ${{ inputs.tag-name }}

    - name: 'Exit if tag is not a version tag'
      if: ${{ steps.check-tag.outputs.is-tag == 'true' }}
      env:
        IS_VERSION: ${{ steps.check-tag.outputs.is-version }}
      run: |
        if [[ "$IS_VERSION" != "true" ]]; then
          exit 1
        fi
      shell: bash
