name: 'Create GitHub release'

inputs:
  token:
    description: 'GitHub token used to create the release'
    default: ${{ github.token }}
  version:
    description: 'The version to release'
    default: ${{ github.ref_name }}
  files:
    description: 'Optional files to include as release assets'
  artifact-name:
    description: 'Optional name of an artifact whose files should be included as release assets'

outputs:
  release-url:
    description: 'HTML URL of the release'
    value: ${{ steps.release.outputs.url }}

runs:
  using: composite
  steps:
    - name: 'Check tag'
      uses: eliashaeussler/gha/.github/actions/assure-version-tag@0.2.3
      with:
        tag-name: ${{ inputs.version }}

    - name: 'Download artifact'
      if: ${{ inputs.artifact-name }}
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: ${{ inputs.artifact-name }}
        path: artifact-download

    - name: 'Create release'
      id: release
      env:
        GH_TOKEN: ${{ inputs.token }}
        VERSION: ${{ inputs.version }}
      run: |
        files=""

        for file in $ADDITIONAL_FILES; do
          files="${files} ${file}"
        done

        if [ -d artifact-download ]; then
          while IFS= read -r -d '' file; do
            files="${files} ${file}"
          done < <(find artifact-download -type f -print0)
        fi

        url="$(gh release create "$VERSION" --generate-notes $files)"

        echo "url=${url}" >> $GITHUB_OUTPUT
      shell: bash
