name: 'Build assets'

inputs:
  command:
    description: 'npm script to build assets'
    default: build

runs:
  using: composite
  steps:
    - name: 'Setup Node'
      uses: eliashaeussler/gha/.github/actions/setup-node@0.7.0

    - name: 'Install npm packages'
      uses: eliashaeussler/gha/.github/actions/npm-install@0.7.0

    - name: 'Build assets'
      env:
        BUILD_COMMAND: ${{ inputs.command }}
      run: npm run "$BUILD_COMMAND"
      shell: bash
