name: 'Build assets'

inputs:
  command:
    description: 'npm script to build assets'
    default: build
  node-env:
    description: 'Node environment (defaults to "production")'
    default: production

runs:
  using: composite
  steps:
    - name: 'Setup Node'
      uses: eliashaeussler/gha/.github/actions/setup-node@0.9.3

    - name: 'Install npm packages'
      uses: eliashaeussler/gha/.github/actions/npm-install@0.9.3

    - name: 'Build assets'
      env:
        BUILD_COMMAND: ${{ inputs.command }}
        NODE_ENV: ${{ inputs.node-env }}
      run: npm run "$BUILD_COMMAND"
      shell: bash
