name: 'Setup PHP environment'

inputs:
  php-version:
    description: 'PHP version to use (defaults to "latest")'
    default: latest
  composer-version:
    description: 'Composer version to use'
  ini-file:
    description: 'php.ini file to use (defaults to "development")'
    default: development
  coverage:
    description: 'Coverage driver to install (defaults to "none")'
    default: none
  tools:
    description: 'Additional tools to install (comma-separated list)'
  extensions:
    description: 'Additional PHP extension to install (comma-separated list)'
  token:
    description: 'GitHub token'
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: 'Compile toolset'
      id: tools
      env:
        COMPOSER_VERSION: ${{ inputs.composer-version }}
        INPUT_TOOLS: ${{ inputs.tools }}
      run: |
        tools="$INPUT_TOOLS"

        if [ -n "$COMPOSER_VERSION" ]; then
          tools="${tools},composer:${COMPOSER_VERSION}"
        fi

        echo "tools=${tools}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: 'Setup PHP'
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        php-version: ${{ inputs.php-version }}
        ini-file: ${{ inputs.ini-file }}
        tools: ${{ steps.tools.outputs.tools }}
        coverage: ${{ inputs.coverage }}
        extensions: ${{ inputs.extensions }}
