name: 'Setup PHP environment'

inputs:
  php-version:
    description: 'PHP version to use (defaults to "latest")'
    default: latest
  ini-file:
    description: 'php.ini file to use (defaults to "development")'
    default: development
  coverage:
    description: 'Coverage driver to install (defaults to "none")'
    default: none
  tools:
    description: 'Additional tools to install (comma-separated list)'
  extensions:
    description: 'Additional PHP extension to install (comma-separated list)'

runs:
  using: composite
  steps:
    - name: 'Setup PHP'
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
      with:
        php-version: ${{ inputs.php-version }}
        ini-file: ${{ inputs.ini-file }}
        tools: ${{ inputs.tools }}
        coverage: ${{ inputs.coverage }}
        extensions: ${{ inputs.extensions }}
