name: 'Run tests with Composer'

inputs:
  command:
    description: 'Composer command to execute'
    default: test

runs:
  using: composite
  steps:
    - name: 'Run tests'
      env:
        TEST_COMMAND: ${{ inputs.command }}
      run: composer ${TEST_COMMAND}
      shell: bash
