name: 'Setup DDEV'

inputs:
  ddev-version:
    description: 'DDEV version to use (defaults to "latest")'
    default: latest
  php-version:
    description: 'PHP version to use'
  start:
    description: 'Whether to start DDEV after installation (defaults to "true")'
    default: 'true'

runs:
  using: composite
  steps:
    - name: 'Setup DDEV'
      uses: ddev/github-action-setup-ddev@fdf2f5c97943bae638f31df6df86f1defa6210c0 # v1.12.1
      with:
        version: ${{ inputs.ddev-version }}
        autostart: false

    - name: 'Configure DDEV'
      env:
        DDEV_ARGS: ${{ case(inputs.php-version != '', format('--php-version={0}', inputs.php-version), '--auto') }}
      run: ddev config $DDEV_ARGS
      shell: bash

    - name: 'Start DDEV'
      if: ${{ inputs.start == 'true' }}
      run: ddev start
      shell: bash

    - name: 'Show DDEV configuration'
      run: ddev describe
      shell: bash
