name: 'Checks'

on:
  workflow_call:
    inputs:
      # Composer
      composer:
        description: 'Perform Composer checks (defaults to "true")'
        default: true
        type: boolean
      php-version:
        description: 'PHP version to use (defaults to "latest")'
        default: latest
        type: string

      # npm
      npm:
        description: 'Perform npm checks (defaults to "false")'
        default: false
        type: boolean
      node-version:
        description: 'Node version to use (defaults to "lts/*")'
        default: 'lts/*'
        type: string
      node-cache:
        description: 'Package manager cache to use (defaults to "npm")'
        default: npm
        type: string
      assets-path:
        description: 'Base path to assets (defaults to project directory)'
        default: .
        type: string

      # Repository
      repository:
        description: 'Perform repository checks (defaults to "true")'
        default: true
        type: boolean
      fail-on-zizmor-findings:
        description: 'Fail if zizmor has found results (defaults to "true")'
        default: true
        type: boolean

jobs:
  composer-checks:
    name: 'Perform Composer checks'
    runs-on: ubuntu-latest

    if: ${{ inputs.composer }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@main

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@main
        with:
          php-version: ${{ inputs.php-version }}

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@main

      - name: 'Perform Composer checks'
        uses: eliashaeussler/gha/.github/actions/composer-checks@main

  npm-checks:
    name: 'Perform npm checks'
    runs-on: ubuntu-latest

    if: ${{ inputs.npm }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@main

      - name: 'Setup Node'
        uses: eliashaeussler/gha/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-cache }}
          base-path: ${{ inputs.assets-path }}

      - name: 'Install npm packages'
        uses: eliashaeussler/gha/.github/actions/npm-install@main
        with:
          base-path: ${{ inputs.assets-path }}

      - name: 'Perform npm checks'
        uses: eliashaeussler/gha/.github/actions/npm-checks@main
        with:
          base-path: ${{ inputs.assets-path }}

  repo-checks:
    name: 'Perform repository checks'
    runs-on: ubuntu-latest

    if: ${{ inputs.repository }}

    permissions:
      contents: read
      security-events: write

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@main

      - name: 'Run zizmor'
        id: zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6

      - name: 'Evaluate zizmor results'
        if: ${{ inputs.fail-on-zizmor-findings }}
        env:
          ZIZMOR_OUTPUT_FILE: ${{ steps.zizmor.outputs.output-file }}
        run: |
          results=$(jq -r '.runs.[0].results | length' "$ZIZMOR_OUTPUT_FILE")

          if [ "$results" -gt 0 ]; then
            echo "::error title=zizmor analysis::The zizmor analysis found ${results} issue(s) in this repository."
            exit 1
          fi
