name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@5f74a39c3bac2c38ddc8b0e9bedd5169d037a9de # main

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@5f74a39c3bac2c38ddc8b0e9bedd5169d037a9de # main
    with:
      composer: false
      npm: false
