name: 'Composer test coverage'

on:
  workflow_call:
    inputs:
      command:
        description: 'Composer command to execute'
        default: 'test:coverage'
        type: string
      coverage-driver:
        description: 'Coverage driver to install (defaults to "pcov")'
        default: pcov
        type: string
      coverage-file:
        description: 'Path to coverage report file'
        default: '.build/coverage/clover.xml'
        type: string
      boot-mysql:
        description: 'Define whether to boot MySQL service'
        type: boolean

jobs:
  collect:
    name: 'Collect test coverage'
    runs-on: ubuntu-latest

    outputs:
      coverage-path: ${{ steps.coverage.outputs.path }}
      coverage-file: ${{ steps.coverage.outputs.file }}

    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: 127.0.0.1
      typo3DatabaseUsername: root
      typo3DatabasePassword: root

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@task/harden

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@0.2.3
        with:
          coverage: ${{ inputs.coverage-driver }}

      - name: 'Start MySQL'
        if: ${{ inputs.boot-mysql }}
        run: sudo /etc/init.d/mysql start

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@0.2.3

      - name: 'Resolve coverage path'
        id: coverage
        env:
          COVERAGE_FILE: ${{ inputs.coverage-file }}
        run: |
          dir=$(dirname "$COVERAGE_FILE")
          file=$(basename "$COVERAGE_FILE")

          echo "path=$dir" >> $GITHUB_OUTPUT
          echo "file=$file" >> $GITHUB_OUTPUT

      - name: 'Create coverage directory'
        env:
          COVERAGE_PATH: ${{ steps.coverage.outputs.path }}
        run: mkdir -p "$COVERAGE_PATH"
        shell: bash

      - name: 'Run tests'
        uses: eliashaeussler/gha/.github/actions/composer-tests@0.2.3
        with:
          command: ${{ inputs.command }}

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage
          path: ${{ inputs.coverage-file }}
          retention-days: 7
          if-no-files-found: error

  report:
    name: 'Report test coverage'
    runs-on: ubuntu-latest

    needs: [collect]

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@task/harden

      - name: 'Download coverage artifact'
        id: download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: coverage

      - name: 'Coveralls report'
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          file: ${{ steps.download.outputs.download-path }}/${{ needs.collect.outputs.coverage-file }}
