name: 'Composer tests'

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to use (defaults to "latest")'
        default: latest
        type: string
      composer-version:
        description: 'Composer version to use'
        type: string
      typo3-version:
        description: 'TYPO3 version to use'
        type: string
      dependencies:
        description: 'Dependency versions to install (defaults to "locked")'
        default: locked
        type: string
      test-command:
        description: 'Composer command to execute'
        default: test
        type: string
      build-command:
        description: 'Optional npm command to execute in order to prebuild assets'
        type: string
      working-directory:
        description: 'Overwrite working directory'
        type: string
      os:
        description: 'Operating system on which to run the workflow (defaults to "Ubuntu")'
        default: Ubuntu
        type: string
      boot-mysql:
        description: 'Define whether to boot MySQL service'
        type: boolean
      composer-options:
        description: 'Additional options passed to "composer install"'
        type: string
      allowed-endpoints:
        description: 'List of allowed outbound endpoints'
        type: string
      phpunit-phar-version:
        description: 'The PHPUnit PHAR version to use (instead of Composer)'
        type: string
      phpunit-phar-flags:
        description: 'Flags passed to PHPUnit PHAR execution'
        default: --no-coverage
        type: string

jobs:
  test:
    name: 'Run tests'
    runs-on: ${{ inputs.os }}-latest

    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: 127.0.0.1
      typo3DatabaseUsername: root
      typo3DatabasePassword: root

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@0.7.4
        with:
          allowed-endpoints: ${{ inputs.allowed-endpoints }}

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@0.7.4
        with:
          php-version: ${{ inputs.php-version }}
          composer-version: ${{ inputs.composer-version }}

      - name: 'Build assets'
        if: ${{ inputs.build-command }}
        uses: eliashaeussler/gha/.github/actions/build-assets@0.7.4
        with:
          command: ${{ inputs.build-command }}

      - name: 'Start MySQL'
        if: ${{ inputs.boot-mysql }}
        run: sudo /etc/init.d/mysql start

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@0.7.4
        with:
          dependencies: ${{ inputs.dependencies }}
          composer-options: >-
            ${{ inputs.composer-version && format('--with=composer/composer:~{0}.0', inputs.composer-version) || '' }}
            ${{ inputs.typo3-version && format('--with=typo3/cms-core:~{0}.0', inputs.typo3-version) || '' }}
            ${{ inputs.composer-options }}
          working-directory: ${{ inputs.working-directory }}

      - name: 'Run tests (using Composer)'
        if: ${{ !inputs.phpunit-phar-version }}
        uses: eliashaeussler/gha/.github/actions/composer-tests@0.7.4
        with:
          command: ${{ inputs.test-command }}
          working-directory: ${{ inputs.working-directory }}

      - name: 'Download PHPUnit PHAR'
        if: ${{ inputs.phpunit-phar-version }}
        env:
          PHPUNIT_PHAR_VERSION: ${{ inputs.phpunit-phar-version }}
        run: |
          wget -O phpunit.phar "https://phar.phpunit.de/phpunit-${PHPUNIT_PHAR_VERSION}.phar"
          wget -O phpunit.phar.asc "https://phar.phpunit.de/phpunit-${PHPUNIT_PHAR_VERSION}.phar.asc"
          gpg --keyserver keys.openpgp.org --recv-keys 0x4AA394086372C20A
          gpg --verify phpunit.phar.asc
          chmod +x phpunit.phar

      - name: 'Run tests (using PHPUnit PHAR)'
        if: ${{ inputs.phpunit-phar-version }}
        env:
          PHPUNIT_PHAR_FLAGS: ${{ inputs.phpunit-phar-flags }}
        run: |
          # shellcheck disable=SC2068
          ./phpunit.phar ${PHPUNIT_PHAR_FLAGS[@]}
