name: 'Composer tests'
on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to use (defaults to "latest")'
        default: latest
        type: string
      dependencies:
        description: 'Dependency versions to install (defaults to "locked")'
        default: locked
        type: string
      command:
        description: 'Composer command to execute'
        default: test
        type: string
      coverage-driver:
        description: 'Coverage driver to install (defaults to "none")'
        default: none
        type: string
      os:
        description: 'Operating system on which to run the workflow (defaults to "Ubuntu")'
        default: Ubuntu
        type: string

jobs:
  test:
    name: 'Run tests'
    runs-on: ${{ inputs.os }}-latest

    outputs:
      coverage-path: ${{ steps.coverage.outputs.path }}
      coverage-file: ${{ steps.coverage.outputs.file }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@e64c74f290c39acc7cdc2fa125478d617b2acc1e # main
        with:
          php-version: ${{ inputs.php-version }}

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@e64c74f290c39acc7cdc2fa125478d617b2acc1e # main
        with:
          dependencies: ${{ inputs.dependencies }}

      - name: 'Run tests'
        uses: eliashaeussler/gha/.github/actions/composer-tests@e64c74f290c39acc7cdc2fa125478d617b2acc1e # main
        with:
          command: ${{ inputs.command }}
