name: 'Composer test coverage'

on:
  workflow_call:
    inputs:
      command:
        description: 'Composer command to execute'
        default: 'test:coverage'
        type: string
      driver:
        description: 'Coverage driver to install (defaults to "pcov")'
        default: pcov
        type: string
      cobertura-file:
        description: 'Path to coverage report file'
        default: '.build/coverage/cobertura.xml'
        type: string

jobs:
  prepare:
    name: 'Prepare workflow'
    runs-on: ubuntu-latest

    outputs:
      continue: ${{ steps.continue.outputs.continue }}

    steps:
      - name: 'Check if workflows is from fork PR'
        id: is-fork
        uses: eliashaeussler/gha/.github/actions/is-fork@main

      - name: 'Check whether to continue current workflow execution'
        id: continue
        env:
          EVENT_NAME: ${{ github.event_name }}
          IS_DEFAULT_REPO: ${{ steps.is-fork.outputs.is-fork != 'true' }}
        run: |
          if [[ "$EVENT_NAME" == "push" ]]; then
            echo "continue=true" >> $GITHUB_OUTPUT
          elif [[ "$EVENT_NAME" == "pull_request" ]]; then
            echo "continue=${IS_ORIGINAL_REPO}" >> $GITHUB_OUTPUT
          else
            echo "continue=false" >> $GITHUB_OUTPUT
          fi

  collect:
    name: 'Collect test coverage'
    runs-on: ubuntu-latest

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    outputs:
      coverage-path: ${{ steps.coverage.outputs.path }}
      cobertura-file: ${{ steps.coverage.outputs.file }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@main
        with:
          coverage: ${{ inputs.driver }}

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@main

      - name: 'Resolve coverage path'
        id: coverage
        env:
          COVERAGE_FILE: ${{ inputs.cobertura-file }}
        run: |
          dir=$(dirname "$COVERAGE_FILE")
          file=$(basename "$COVERAGE_FILE")

          echo "path=$dir" >> $GITHUB_OUTPUT
          echo "file=$file" >> $GITHUB_OUTPUT

      - name: 'Create coverage directory'
        env:
          COVERAGE_PATH: ${{ steps.coverage.outputs.path }}
        run: mkdir -p "$COVERAGE_PATH"
        shell: bash

      - name: 'Run tests'
        uses: eliashaeussler/gha/.github/actions/composer-tests@main
        with:
          command: ${{ inputs.command }}

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage
          path: ${{ inputs.cobertura-file }}
          retention-days: 7

  report:
    name: 'Report test coverage'
    runs-on: ubuntu-latest

    needs: [collect]

    permissions:
      code-quality: write
      contents: read
      pull-requests: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: 'Download coverage artifact'
        id: download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: coverage

      - name: 'Upload coverage report'
        uses: actions/upload-code-coverage@b51da2c3c1b23e04d2d6477cfc34350b1f5cd3e9 # v1
        with:
          file: ${{ steps.download.outputs.download-path }}/${{ needs.collect.outputs.cobertura-file }}
          language: PHP
          label: 'code-coverage/php'
