name: Crowdin

on:
  workflow_call:
    secrets:
      CROWDIN_TOKEN:
        description: 'Personal Crowdin token used to upload language sources'
        required: true

    inputs:
      project-id:
        description: 'Crowdin project ID'
        required: true
        type: number
      config-file:
        description: 'Path to crowdin.yaml'
        default: '.crowdin.yaml'
        type: string
      branch-name:
        description: 'Crowdin branch name (defaults to "main")'
        default: main
        type: string

jobs:
  sync:
    name: 'Synchronize with Corwdin'
    runs-on: ubuntu-latest

    if: ${{ github.ref_name == github.event.repository.default_branch }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@0.7.4

      - name: 'Upload sources'
        uses: crowdin/github-action@52aa776766211d83d975df51f3b9c53c2f8ba35f # v2.16.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          config: ${{ inputs.config-file }}
          project_id: ${{ inputs.project-id }}
          token: ${{ secrets.CROWDIN_TOKEN }}
          crowdin_branch_name: ${{ inputs.branch-name }}
