name: 'DevSecOps'

on:
  workflow_call:
    secrets:
      DEVGUARD_TOKEN:
        description: 'DevGuard API token'
        required: true

    inputs:
      devguard-asset-name:
        description: 'Asset name of the repository used in DevGuard'
        required: true
        type: string

permissions:
  contents: read

jobs:
  secret-scanning:
    name: 'Secret scanning'

    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}

    uses: l3montree-dev/devguard-ci-components/.github/workflows/secret-scanning.yml@3c35e3524f0c0abb375c111530114faafd6772f7 # v1.13.0
    with:
      devguard-asset-name: ${{ inputs.devguard-asset-name }}

  dependency-scanning:
    name: 'Dependency scanning'

    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}

    uses: l3montree-dev/devguard-ci-components/.github/workflows/software-composition-analysis.yml@3c35e3524f0c0abb375c111530114faafd6772f7 # v1.13.0
    with:
      devguard-asset-name: ${{ inputs.devguard-asset-name }}

  sast:
    name: 'SAST'

    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}

    uses: l3montree-dev/devguard-ci-components/.github/workflows/static-application-security-testing.yml@3c35e3524f0c0abb375c111530114faafd6772f7 # v1.13.0
    with:
      devguard-asset-name: ${{ inputs.devguard-asset-name }}
