name: Preparation

on:
  workflow_call:
    outputs:
      continue:
        description: 'Describes whether to continue current workflow execution ("true" on non-PR events and forks, "false" otherwise).'
        value: ${{ jobs.prepare.outputs.continue }}

jobs:
  prepare:
    name: 'Prepare workflow'
    runs-on: ubuntu-latest

    outputs:
      continue: ${{ steps.continue.outputs.continue }}

    steps:
      - name: 'Check whether to continue current workflow execution'
        id: continue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            if (context.eventName === 'pull_request') {
              const payload = context.payload.pull_request;
              core.setOutput('continue', payload.base.repo.owner.login !== payload.head.repo.owner.login);
            } else {
              core.setOutput('continue', true);
            }
