name: Preparation

on:
  workflow_call:
    outputs:
      continue:
        description: 'Describes whether to continue current workflow execution ("true" on non-PR events and forks, "false" otherwise).'
        value: ${{ jobs.prepare.outputs.continue }}

jobs:
  prepare:
    name: 'Prepare workflow'
    runs-on: ubuntu-latest

    outputs:
      continue: ${{ steps.continue.outputs.continue }}

    steps:
      - name: 'Check if workflow is from fork PR'
        id: is-fork
        uses: eliashaeussler/gha/.github/actions/is-fork@0.6.2

      - name: 'Check whether to continue current workflow execution'
        id: continue
        env:
          EVENT_NAME: ${{ github.event_name }}
          IS_FORK: ${{ steps.is-fork.outputs.is-fork }}
        run: |
          if [[ "$EVENT_NAME" == "pull_request" ]]; then
            echo "continue=${IS_FORK}" >> "$GITHUB_OUTPUT"
          else
            echo "continue=true" >> "$GITHUB_OUTPUT"
          fi
