name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: 'Create release'

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@0.3.8
