name: 'Merge Renovate branch'

on:
  workflow_call:
    secrets:
      MERGE_TOKEN:
        description: 'GitHub token used to merge branches'
        required: true

env:
  CURRENT_BRANCH: ${{ github.ref_name }}
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  prepare:
    name: 'Prepare workflow execution'
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.ref_name, 'renovate/') }}

    outputs:
      continue: ${{ steps.is-renovate.outputs.is-renovate == 'false' && steps.is-fork.outputs.is-fork == 'false' && steps.has-pr.outputs.has-pr == 'false' }}

    steps:
      - name: 'Check if workflow is from Renovate'
        id: is-renovate
        uses: eliashaeussler/gha/.github/actions/is-renovate@1.1.0

      - name: 'Check if workflow is from fork PR'
        id: is-fork
        uses: eliashaeussler/gha/.github/actions/is-fork@1.1.0

      - name: 'Check if PR exists for branch'
        id: has-pr
        uses: eliashaeussler/gha/.github/actions/has-pr@1.1.0

  merge:
    name: 'Merge Renovate branch into default branch'
    runs-on: ubuntu-latest

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@1.1.0
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          fetch-depth: 0
          # Must be true, otherwise new commits cannot be pushed
          persist-credentials: true

      - name: 'Prepare Git environment'
        uses: eliashaeussler/gha/.github/actions/setup-git@1.1.0

      - name: 'Merge changes into default branch'
        run: |
          git fetch origin "$DEFAULT_BRANCH"
          git checkout "$DEFAULT_BRANCH"
          git merge --no-ff --no-edit "$CURRENT_BRANCH"
          git push origin "$DEFAULT_BRANCH"

      - name: 'Delete merged branch'
        run: git push origin --delete "$CURRENT_BRANCH"
