name: 'Prepare TYPO3 tests'

on:
  workflow_call:
    inputs:
      typo3-version:
        description: 'TYPO3 version to use'
        type: string

    outputs:
      has-acceptance-tests:
        description: 'Whether acceptance tests are available'
        value: ${{ jobs.prepare.outputs.has-acceptance-tests }}
      has-functional-tests:
        description: 'Whether functional tests are available'
        value: ${{ jobs.prepare.outputs.has-functional-tests }}
      has-unit-tests:
        description: 'Whether unit tests are available'
        value: ${{ jobs.prepare.outputs.has-unit-tests }}
      test-command:
        description: 'Base command to run tests (e.g. "composer" or "ddev composer")'
        value: ${{ jobs.prepare.outputs.test-command }}
      use-ddev:
        description: 'Whether to use DDEV to run tests'
        value: ${{ jobs.prepare.outputs.use-ddev }}
      requires-compatibility-update:
        description: 'Whether to run compatibility update for mismatching TYPO3 / class-alias-loader versions'
        value: ${{ jobs.prepare.outputs.requires-compatibility-update }}

jobs:
  prepare:
    name: 'Prepare tests'
    runs-on: ubuntu-latest

    outputs:
      has-acceptance-tests: ${{ steps.testsuites.outputs.acceptance }}
      has-functional-tests: ${{ steps.testsuites.outputs.functional }}
      has-unit-tests: ${{ steps.testsuites.outputs.unit }}
      test-command: ${{ steps.context.outputs.command }}
      use-ddev: ${{ steps.context.outputs.use-ddev }}
      requires-compatibility-update: ${{ steps.compatibility.outputs.compatible == 'false' }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@1.1.6

      - name: 'Lookup testsuites'
        id: testsuites
        run: |
          commands="$(composer list --format json)"

          function hasCommand() {
            echo "$commands" | jq -r "if (.commands | map(select(.name == \"$1\")) | length) == 0 then \"false\" else \"true\" end"
          }

          {
            echo "acceptance=$(hasCommand 'test:acceptance')"
            echo "functional=$(hasCommand 'test:functional')"
            echo "unit=$(hasCommand 'test:unit')"
          } >> "$GITHUB_OUTPUT"

      - name: 'Determine execution context'
        id: context
        env:
          HAS_ACCEPTANCE_TESTS: ${{ steps.testsuites.outputs.acceptance }}
        run: |
          if [[ "$HAS_ACCEPTANCE_TESTS" == "true" ]]; then
            command="ddev composer"
            useDDEV="true"
          else
            command="composer"
            useDDEV="false"
          fi

          echo "command=${command}" >> "$GITHUB_OUTPUT"
          echo "use-ddev=${useDDEV}" >> "$GITHUB_OUTPUT"

      - name: 'Resolve class-loader compatibility'
        id: compatibility
        env:
          TYPO3_VERSION: ${{ inputs.typo3-version }}
        run: |
          function fetchLockedVersion() {
            composer show "$1" --locked --format json | jq -r '.versions[0] | ltrimstr("v") | split(".")[0]'
          }

          if [ -z "$TYPO3_VERSION" ]; then
            TYPO3_VERSION="$(fetchLockedVersion typo3/cms-core)"
          fi

          classLoaderVersion="$(composer show typo3/class-alias-loader --locked --format json | jq -r '.versions[0] | ltrimstr("v") | split(".")[0]')"
          typo3Version="$(echo "$TYPO3_VERSION" | cut -d'.' -f1)"

          if [ "$classLoaderVersion" -ge 2 ]; then
            # typo3/class-alias-loader v2

            if [ "$typo3Version" -ge 14 ]; then
              compatible="true"
            else
              compatible="false"
            fi
          else
            # typo3/class-alias-loader v1

            if [ "$typo3Version" -ge 14 ]; then
              compatible="false"
            else
              compatible="true"
            fi
          fi

          echo "compatible=${compatible}" >> "$GITHUB_OUTPUT"
        shell: bash
