name: 'TYPO3 test coverage'

on:
  workflow_call:
    inputs:
      ddev-version:
        description: 'DDEV version to use (defaults to "latest")'
        default: latest
        type: string
      acceptance-report-path:
        description: 'Path to acceptance reports'
        default: Build/tests/log/acceptance-reports
        type: string
      coverage-file:
        description: 'Path to coverage report file'
        default: Build/tests/coverage/clover.xml
        type: string
      allowed-endpoints:
        description: 'List of allowed outbound endpoints'
        type: string

jobs:
  prepare:
    name: 'Prepare tests'

    permissions:
      contents: read

    uses: eliashaeussler/gha/.github/workflows/typo3-test-preparation.yaml@1.0.1

  collect:
    name: 'Collect test coverage'
    runs-on: ubuntu-latest

    needs: [prepare]

    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: 127.0.0.1
      typo3DatabaseUsername: root
      typo3DatabasePassword: root

    outputs:
      coverage-path: ${{ steps.coverage.outputs.path }}
      coverage-file: ${{ steps.coverage.outputs.file }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@1.0.1
        with:
          egress-policy: ${{ case(needs.prepare.outputs.has-acceptance-tests == 'true', 'audit', 'block') }}
          allowed-endpoints: ${{ inputs.allowed-endpoints }}

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@1.0.1
        with:
          coverage: ${{ case(needs.prepare.outputs.use-ddev == 'true', 'none', 'pcov') }}

      - name: 'Setup DDEV'
        if: ${{ needs.prepare.outputs.use-ddev == 'true' }}
        uses: eliashaeussler/gha/.github/actions/setup-ddev@1.0.1
        with:
          ddev-version: ${{ inputs.ddev-version }}

      - name: 'Start MySQL'
        if: ${{ needs.prepare.outputs.use-ddev == 'false' && needs.prepare.outputs.has-functional-tests == 'true' }}
        run: sudo /etc/init.d/mysql start

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@1.0.1

      - name: 'Resolve coverage path'
        id: coverage
        env:
          COVERAGE_FILE: ${{ inputs.coverage-file }}
        run: |
          dir=$(dirname "$COVERAGE_FILE")
          file=$(basename "$COVERAGE_FILE")

          echo "path=$dir" >> "$GITHUB_OUTPUT"
          echo "file=$file" >> "$GITHUB_OUTPUT"

      - name: 'Create coverage directory'
        env:
          COVERAGE_PATH: ${{ steps.coverage.outputs.path }}
        run: mkdir -p "$COVERAGE_PATH"

      - name: 'Run functional tests'
        if: ${{ needs.prepare.outputs.has-functional-tests == 'true' }}
        env:
          COMMAND: ${{ needs.prepare.outputs.test-command }}
        run: $COMMAND test:functional:coverage

      - name: 'Run unit tests'
        if: ${{ needs.prepare.outputs.has-unit-tests == 'true' }}
        env:
          COMMAND: ${{ needs.prepare.outputs.test-command }}
        run: $COMMAND test:unit:coverage

      - name: 'Run acceptance tests'
        if: ${{ needs.prepare.outputs.has-acceptance-tests == 'true' }}
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          command: '${{ needs.prepare.outputs.test-command }} test:acceptance:coverage'

      - name: 'Merge coverage reports'
        env:
          COMMAND: ${{ needs.prepare.outputs.test-command }}
        run: $COMMAND test:merge-coverage

      - name: 'Fix coverage path'
        if: ${{ needs.prepare.outputs.use-ddev == 'true' }}
        working-directory: ${{ steps.coverage.outputs.path }}
        env:
          COVERAGE_FILE: ${{ steps.coverage.outputs.file }}
          GH_WORKSPACE: ${{ github.workspace }}
        run: sed -i "s#/var/www/html#${GH_WORKSPACE}#g" "$COVERAGE_FILE"

      - name: 'Save acceptance reports'
        if: ${{ needs.prepare.outputs.has-acceptance-tests == 'true' && failure() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: acceptance-reports-coverage
          path: |
            ${{ steps.coverage.outputs.path }}
            var/log

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: ${{ inputs.coverage-file }}
          retention-days: 7
          if-no-files-found: error

  report:
    name: 'Report test coverage'
    runs-on: ubuntu-latest

    needs: [collect]

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@1.0.1

      - name: 'Download coverage artifact'
        id: download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage

      - name: 'Coveralls report'
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          file: ${{ steps.download.outputs.download-path }}/${{ needs.collect.outputs.coverage-file }}
